<?php $_helper = $this->helper('catalog/output'); ?>
<?php $featureds = $this->helper('jollyanytheme')->getFeaturedProducts() ?>
<?php if($featureds && count($featureds)>0): ?>


	<div class="general-title padding-top">
		<h2><?php echo $this->__('Featured Products') ?></h2>
		<hr class="no-padding"/>
	</div>
	
	<div class="shop_wrapper padding-top">
		<?php $i=0; foreach($featureds as $_product): $i++ ?>
			<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12<?php if($i==1): ?> first<?php endif ?>">
				<div class="shop_item">
					<div class="entry">
						<?php if($_product->getProductLabel()): ?>
							<div class="triangle <?php echo strtolower($_product->getAttributeText('product_label')) ?>">
								<span class="onsale"><?php echo $_product->getAttributeText('product_label') ?></span>
							</div>
						<?php endif ?>
						<img alt="" class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(600,600); ?>">
						
						<div class="magnifier">
							<div class="buttons">
								<a href="<?php echo $this->helper('checkout/cart')->getAddUrl($_product); ?>" class="st btn btn-default" rel="bookmark">
									<?php echo $this->__('Add to Cart') ?>
								</a>
								<p class="tooltips">
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<a class="st wishlist-link" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-placement="bottom" data-toggle="tooltip" data-original-title="<?php echo $this->__('Wishlist') ?>">
											<span class="fa fa-heart"></span>
										</a>
									<?php endif; ?>
									
									<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
										<a class="st" href="<?php echo $_compareUrl ?>" data-placement="bottom" data-toggle="tooltip" data-original-title="<?php echo $this->__('Compare') ?>">
											<span class="fa fa-retweet"></span>
										</a>
									<?php endif; ?>
								</p>
								
							</div>
						</div>
					</div>
					<div class="shop_desc">
						<div class="shop_title pull-left">
							<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"><span>
								<?php echo Mage::helper('core/string')->truncate($_helper->productAttribute($_product, $_product->getName(), 'name'), 35) ?>
							</span></a>
							<span class="cats"><?php echo $this->helper('jollyanytheme')->getCategoriesOfProduct($_product) ?></span>
						</div>
					</div>
					<div>
						<span class="price">
							<?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?>
							<?php if($_product->getFinalPrice()<$_product->getPrice()): ?>
								<span class="old-price"><?php echo Mage::helper('core')->currency($_product->getPrice(),true,false); ?></span>
							<?php endif ?>
						</span>
					</div>
				</div>
			</div>
		<?php endforeach ?>
	</div>
<?php endif ?>