<div class="widget">
	<div class="title">
		<h3><?php echo $this->__('Newsletter') ?></h3>
	</div><!-- end title -->
	<div class="newsletter_widget">
		<p><?php echo $this->__("Subscribe to our newsletter to receive news, updates, free stuff and new releases by email. We don't do spam..") ?></p>
		<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail-home" class="newsletter_form">
			<input type="text" name="email" id="newsletter" class="form-control required-entry validate-email" placeholder="<?php echo $this->__('Enter your email address') ?>">
			<button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="btn btn-primary pull-right"><?php echo $this->__('Subscribe') ?></button>
		</form><!-- end newsletter form -->
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	var newsletterSubscriberFormDetailHome = new VarienForm('newsletter-validate-detail-home');
//]]>
</script>