<?php if(Mage::getStoreConfig('jollyanytheme/contact/enabled')): ?>
	<?php $latitude = Mage::getStoreConfig('jollyanytheme/contact/latitude') ?>
	<?php $longitude = Mage::getStoreConfig('jollyanytheme/contact/longitude') ?>
	<?php if(($latitude != '') && ($longitude != '')): ?>
		<?php $html = Mage::getStoreConfig('jollyanytheme/contact/html') ?>
		<?php $image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'jollyany/'.Mage::getStoreConfig('jollyanytheme/contact/image') ?>
	
		<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<script type="text/javascript">
			var locations = [
			['<?php echo $html ?>', <?php echo $latitude ?>, <?php echo $longitude ?>, 2]
			];
		
			var map = new google.maps.Map(document.getElementById('map'), {
			  zoom: 14,
				scrollwheel: false,
				navigationControl: true,
				mapTypeControl: false,
				scaleControl: false,
				draggable: true,
				styles: [ { "stylers": [ { "hue": "#000" },  {saturation: -100},
					{gamma: 0.50} ] } ],
				center: new google.maps.LatLng(<?php echo $latitude ?>, <?php echo $longitude ?>),
			  mapTypeId: google.maps.MapTypeId.ROADMAP
			});
		
			var infowindow = new google.maps.InfoWindow();
		
			var marker, i;
		
			for (i = 0; i < locations.length; i++) {  
		  
				marker = new google.maps.Marker({ 
				position: new google.maps.LatLng(locations[i][1], locations[i][2]), 
				map: map ,
				icon: '<?php echo $image ?>'
				});
		
		
			  google.maps.event.addListener(marker, 'click', (function(marker, i) {
				return function() {
				  infowindow.setContent(locations[i][0]);
				  infowindow.open(map, marker);
				}
			  })(marker, i));
			}
	  </script>
	<?php endif ?>
<?php endif ?>